services:
  myazeroth-account:
    image: accendl/account
    ports:
      - "8105:8105"
      - "20885:20885"
    networks:
      azeroth:
        ipv4_address: 172.20.0.5
    volumes:
      - myazeroth-log-data:/log

  myazeroth-azeroth:
    image: accendl/azeroth
    ports:
      - "8104:8104"
      - "20884:20884"
    networks:
      azeroth:
        ipv4_address: 172.20.0.4
    volumes:
      - myazeroth-log-data:/log

  myazeroth-food:
    image: accendl/food
    ports:
      - "8109:8109"
      - "20889:20889"
    networks:
      azeroth:
        ipv4_address: 172.20.0.9
    volumes:
      - myazeroth-log-data:/log

  myazeroth-mail:
    image: accendl/mail
    ports:
      - "8106:8106"
      - "20886:20886"
    networks:
      azeroth:
        ipv4_address: 172.20.0.6
    volumes:
      - myazeroth-log-data:/log
      - accendl-mail-data:/image:ro

  myazeroth-rocketmq-producer:
    image: accendl/rocketmq-producer
    ports:
      - "8107:8107"
      - "20887:20887"
    networks:
      azeroth:
        ipv4_address: 172.20.0.7
    volumes:
      - myazeroth-log-data:/log

  myazeroth-rocketmq-consumer:
    image: accendl/rocketmq-consumer
    ports:
      - "8108:8108"
      - "20888:20888"
    networks:
      azeroth:
        ipv4_address: 172.20.0.8
    volumes:
      - myazeroth-log-data:/log
    depends_on:
      - myazeroth-rocketmq-producer
      - myazeroth-mail

  myazeroth-web:
    image: accendl/web
    ports:
      - "8102:8102"
      - "20882:20882"
    networks:
      azeroth:
        ipv4_address: 172.20.0.2
    volumes:
      - myazeroth-log-data:/log
    depends_on:
      - myazeroth-rocketmq-producer
      - myazeroth-food
      - myazeroth-account
      - myazeroth-azeroth

networks:
  azeroth:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  myazeroth-log-data:
    external: true
  accendl-mail-data:
    external: true
