spring:
  application:
    name: rocketmq-tx-producer
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 10.0.4.4:9876,10.0.4.9:9876,10.0.4.15:9876
        bindings:
          producer-out-0:
            producer:
              group: output_0
              transactionListener: myTransactionListener
              producerType: Trans
          producer-out-1:
            producer:
              group: output_1
              transactionListener: myTransactionListener
              producerType: Trans
      bindings:
        producer-out-0:
          destination: tx-accountCreate
        producer-out-1:
          destination: tx-sendBase32Key

logging:
  level:
    org.springframework.context.support: debug
