pipeline {
    agent any
    environment {
        JAVA_HOME='/var/jenkins_home/jdk17-1/jdk-17'
    }
    stages {
        stage('init'){
            steps {
                sh 'pwd'
                sh 'chmod +x gradlew'
                sh 'printenv'
            }

        }
        stage('Compile') {
            steps {
                gradlew('clean')
                gradlew('classes')
            }
        }
        stage('Assemble') {
            steps {
                gradlew('assemble')
                gradlew('publish')
                stash includes: '**/mail/build/libs/*.jar', name: 'app'
            }
        }
        stage('Promotion') {
            steps {
                timeout(time: 1, unit:'DAYS') {
                    input 'Deploy to Production?'
                }
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker build -f mail/Dockerfile -t accendl/mail .'
                sh 'cat /var/jenkins_home/my_docker_password.txt | docker login --username accendl --password-stdin'
                sh 'docker image push accendl/mail'
            }
        }
    }
}

def gradlew(String... args) {
    sh "./gradlew :mail:${args.join(' ')} -s"
}