pipeline {
    agent any
    environment {
        JAVA_HOME='/var/jenkins_home/jdk17-1/jdk-17'
    }
    stages {
        stage('init'){
            steps {
                sh 'pwd'
                sh 'chmod +x gradlew'
                sh 'printenv'
            }

        }
        stage('Compile') {
            steps {
                gradlew('clean')
                gradlew('classes')
            }
        }
        stage('Assemble') {
            steps {
                gradlew('assemble')
                gradlew('publish')
                stash includes: '**/rocketmq-consumer/build/libs/*.jar', name: 'app'
            }
        }
        stage('Promotion') {
            steps {
                timeout(time: 1, unit:'DAYS') {
                    input 'Deploy to Production?'
                }
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker build -f rocketmq-consumer/Dockerfile -t accendl/rocketmq-consumer .'
            }
        }
    }
}

def gradlew(String... args) {
    sh "./gradlew :rocketmq-consumer:${args.join(' ')} -s"
}